config/routes.rb
LifeAdvisor::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "user_home/index"
	get 'home' => "user_home#index"
  get "welcome/index"

	root :to => 'action_items#index'

  controller :action_items do
    get 'action_items/completed' => :completed
    get 'action_items/all' => :all
    post 'action_items/toggle_done/:id' => :toggle_done
    post 'action_items/:id/category/:category' => :category_update
    post 'action_items/category_update_all' => :category_update_all
    post 'action_items/:id/bump' => :bump
    put 'action_items/:id/bump' => :bump
    put 'action_items/:id/to_link' => :to_link
  end
  resources :action_items
  resources :questions
  controller :questions do
    post 'questions/:id/bump' => :bump
  end
  
  resources :answers
  resources :people
  
  controller :web_links do
    get 'web_links/bookmark' => :bookmark
    post 'web_links/bookmark' => :create_bookmark
    put 'web_links/:id/to_action_item' => :to_action_item
  end
  
  controller :projects do
    get 'projects/completed'
    get 'projects/canceled'
    post 'projects/:id/status/:status' => :status_update
    get 'projects/:id/set_goals' => :set_goals
    post 'projects/:project_key/serve_goal_toggle/:goal_key' => :serve_goal_toggle
    post 'projects/:id/bump' => :bump
  end
  resources :projects
  resources :history
  resources :web_links
  resources :thoughts
  resources :goals
  

  
  controller :focus do
    get 'focus/:area' => :focus_area
  end

  controller :goals do
    post 'goals/:id/bump' => :bump
  end

  resources :current_focus do
    collection do
      post 'edit'
      post 'reset'
    end
  end
  

  

end

app/models/project.rb
require 'RippleSearch'
require 'Parentable'
require 'Util'
require 'Bumpable'

class Project
  include Ripple::Document
  include Comparable
  include Parentable
  extend RippleSearch
  include Bumpable
  
  property :name, String, :presence => true
  property :description, String
  property :url, String
  property :status, String, :default => :idea  # One of [:idea, :active, :someday, :canceled, :completed]
  property :completed_at, Time
  property :canceled_at, Time
  property :area, String, :default => :admin # Realms/Areas of concern. One of [:soul, :work, :admin, :assistant ]
  property :related_projects, Set
  
  timestamps!
  
  def to_hash
    JSON.parse(self.to_json)
  end
  
  def to_hash_for_export
    proj_hash = self.to_hash
    hash_for_export = {}
    hash_for_export['key'] = self.key
    hash_for_export['name'] = self.name
    proj_hash.keys.each do | attribute |
      unless hash_for_export.include? attribute.to_s
        hash_for_export[attribute.to_s] = proj_hash[attribute]
      end
    end
    
    questions = []
    self.questions().each do | question |
      question_hash = { 'key' => question.key, 'name' => question.name || '' }
      questions.append(question_hash)
    end
    hash_for_export['questions'] = questions
    
    action_items = { 'todo' => [], 'completed' => [] }
    self.action_items.each do | item |
      if item.done
        action_items['completed'].append({ 'key'=>item.key, 'name'=>item.name})
      else
        action_items['todo'].append({ 'key'=>item.key, 'name'=>item.name})
      end
    end
    hash_for_export['action_items'] = action_items
    
    links = []
    self.links().each do | link |
      link_hash = { 'key' => link.key, 'name' => link.name || '', 'url'=> link.url }
      links.append(link_hash)
    end
    hash_for_export['links'] = links
    hash_for_export
  end
  
  def <=>(anOther)
    # First, sort in reverse bump_count order
    unless self.bump_count == anOther.bump_count 
      return anOther.bump_count <=> self.bump_count
    end
    
    # Lastly, sort alpha by name, ascending
    self.name <=> anOther.name
  end
  
  def action_items
    @action_items ||= ActionItem.for_parent(:project, self.key)
  end
  
  def action_items_completed
    self.action_items.select { |item| item.done }
  end

  def action_items_todo
    self.action_items.select { |item| not item.done }
  end
  
  def add_goal(goal_key)
    project_goal = ProjectGoal.new project_key: self.key, goal_key: goal_key
    project_goal.save
  end
  
  def add_related_project(proj_key)
    
  end
  
  def change_status!(new_status)
    self.status = new_status
    if new_status.to_sym == :completed
      self.completed_at = Time.now
      self.canceled_at = nil
    elsif new_status.to_sym == :canceled
      self.canceled_at = Time.now
      self.completed_at = nil
    else
      self.completed_at = nil
      self.canceled_at = nil
    end
  end
  
  def current_focus!
    Elefsis.focus_on self
  end
  
  def destroy_links!
    self.links.each do | link |
      link.destroy!
    end
  end
  
  # Does this project have related projects?
  # @return [Boolean] True if this project has related projects linked to it.
  def has_related?
    self.related_projects.present?
  end
  
  def goal_ids
    goal_docs = self.project_goals
    goal_ids = goal_docs.collect {|g| g['goal_key'] }
  end
  
  def goals_served
    Goal.find(self.goal_ids)
  end
  
  def links
    WebLink.for_parent(:project, self.key)
  end
  
  def new_link(link_params)
    link = WebLink.new(link_params)
    link.parent_type = :project
    link.parent_key = self.key
    link
  end
  
  def next_action
    project_items_todo = self.action_items_todo.sort
    if project_items_todo.present?
      next_action = project_items_todo.first
    end
    next_action
  end
  
  def project_goals
    search_string = "project_key:#{self.key}"
    goal_docs = ProjectGoal.search_results_for(search_string)
  end
  
  # Hash by ProjectGoal key
  def project_goals_hash
    project_goals = self.project_goals
    project_goals = project_goals.map { |doc| ProjectGoal.from_search_result(doc) }
    project_goals_hash = Hash[project_goals.map {|pg| [pg.goal_key, pg]}]
  end
  
  def questions
    Question.for_parent(:project, self.key)
  end
  
  # Lazy-initialize accessor to :related_projects
  def related_projects
    @related_projects ||= []
  end
  
  def serve_goal_toggle(goal_key)
    goals_hash = self.project_goals_hash
    goal_ids = goals_hash.keys
    if goal_ids.include? goal_key
      # Stop serving goal - Delete the project-goal association
      project_goal_key = goals_hash[goal_key].key
      project_goal = ProjectGoal.find(project_goal_key)
      project_goal.destroy
    else
      project_goal = ProjectGoal.new(goal_key: goal_key, project_key: self.key)
      project_goal.save
    end
  end
  
  def time_elapsed(action_items)
    action_items.map(&:time_elapsed).sum
  end
  
  def self.active_projects
    self.all_for_status(:active)
  end
  
  def self.all_for_status(status)
    search_string = "status:"+status.to_s
    results = self.search_results_for(search_string)
    results.collect { |doc| Project.from_search_result(doc) }
  end
    
  def self.focus_on_area(area, status=:active)
    search_string = "status:#{status} AND area:#{area}"
    results = self.search_results_for(search_string)
    results.collect { |doc| Project.from_search_result(doc) }
  end
  
  def self.hash_by_status(projects)
    Util.hash_list_by(projects,:status)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
#    @projects = Project.all
    @idea_projects = Project.all_for_status(:idea).sort
    @active_projects = Project.all_for_status(:active).sort
    @someday_projects = Project.all_for_status(:someday).sort

    respond_to do |format|
      format.html # index.html.erb
#      format.json { render json: @projects }
    end
  end

  def all
    @all_items = Project.all # list keys
    
    respond_to do |format|
      format.html # all.html.erb
      format.json { render json: @all_items }
    end
  end

  def canceled
    @canceled_projects = Project.all_for_status(:canceled)
    respond_to do |format|
      format.html # canceled.html.erb
    end
  end
    
  def completed
    @completed_projects = Project.all_for_status(:completed)
    respond_to do |format|
      format.html # completed.html.erb
    end
  end
  
  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @next_action = @project.next_action
    @action_items = @project.action_items_todo.sort
    @completed_items = @project.action_items_completed.sort {|x,y| y <=> x}
    @num_action_items_total = @action_items.count + @completed_items.count
    @elapsed_time_completed = @project.time_elapsed(@completed_items)
    @elapsed_time_todo = @project.time_elapsed(@action_items)
    @elapsed_time_total = @elapsed_time_completed + @elapsed_time_todo
    
    @links = @project.links
    @questions = @project.questions.sort
    @goals_served = @project.goals_served
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def serve_goal_toggle
    goal_key = params[:goal_key]
    project_key = params[:project_key]
    project = Project.find(project_key)
    project.serve_goal_toggle(goal_key)
    render :nothing => true
  end
  
  def set_goals
    @project = Project.find(params[:id])
    @goal_ids = @project.goal_ids
    @active_goals = Goal.active_goals
    
    respond_to do |format|
      format.html # set_goals.html.erb
    end
  end
  
  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
#        redirect_url = projects_url + "#project-" + @project.key
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def bump
    @project = Project.find(params[:id])
    @project.bump!
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Bumped '#{@project.name}'"}
    end
  end
  
  def status_update
    @project = Project.find(params[:id])
    @project.change_status! params[:status]
    
    if @project.status.to_sym == :completed
      new_url = '/projects/completed'
    elsif @project.status.to_sym == :canceled
      new_url = '/projects/canceled'
    else
      new_url = @project
    end
      
    respond_to do |format|
      if @project.save
        format.html { redirect_to new_url }
      end
    end
  end
  
  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
#        redirect_url = projects_url  + "#project-" + @project.key
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params[:project].permit(:name, :description, :status, :area, :parent_type, :parent_key, :url, :bump_count)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_active.html.erb
<h4 class="text-center">Active Projects</h4>
<div style="text-align: center;">
<% projects.each do | project | %>
  <% next_action = project.next_action %>
  <div style="display: inline-block; padding: 1em; border: 1px solid #DDD;">
    <span class="area-<%= project.area %>"><%= link_to project.name, project_path(project) %></span>
    <% if next_action %>
      <br />
      <span class="small"><%= link_to 'Next:', action_item_path(next_action) %> <%= next_action.name %></span>
    <% end %>
  </div>
<% end %>
</div>
  <div style="clear: both;"><br /></div>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => { :class => "form-horizontal"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
    <%= f.text_field :name, :class=> "project" %><br />
    </div>
</div>

<div class="control-group">
    <%= f.label :url, class: "control-label" %>
    <div class="controls">
    <%= f.text_field :url, :class=> "project" %><br />
    </div>
</div>

<div class="control-group">
    <%= f.label :bump_count, class: "control-label" %>
    <div class="controls">
    <%= f.text_field :bump_count, :class=> "project" %><br />
    </div>
</div>

<%= render partial: 'action_items/area_select', locals: { form: f } %>

<div class="control-group">
    <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, :class=> "project", :rows => 5 %><br />
  </div>
</div>

<div class="control-group">
  <div class="actions controls">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/projects/_new.html.erb
<%= form_for(Project.new, :html => { :class => "form-inline inline"}) do |f| %>
    <%= f.text_field :name, :class=> "project", :tabindex => 1, :autofocus => true %>
    <%= f.hidden_field :area, value: area %>
    <%= f.submit 'Add Project', :class=> "project btn" %>
<% end %>

app/views/projects/_project.html.erb
  <% action_items = project.action_items %>
  <% item_count = action_items.count %>
  <% link_count = project.links.count %>
  <% next_action = project.next_action %>
  <% time_elapsed = project.time_elapsed(action_items) %>
  <tr>
    <td class="span1 nowrap">
    <% if item_count > 0 %>
      [ <%= project.action_items_completed.count %> / <%= item_count %> ]
      <% if link_count > 0 %>
        <br />
        <span class="muted small"><%= link_count %> links</span>
      <% end %>
    <% end %>
    </td>
    <td class="span6" id="project-<%= project.key %>">
      <%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-mini'  %>
      <span class="area-<%= project.area %>"><%= link_to project.name, project_path(project) %></span>
      <% if next_action %>
        <br />
        <%= link_to 'Next Action:', action_item_path(next_action) %> <%= next_action.name %>
      <% end %>
    </td>
    <td>
      <%= render(partial: 'projects/status_buttons_'+project_status.to_s, locals: { project: project } ) %>
    </td>
    <td>
      <% if time_elapsed > 0 %>
        <%= time_elapsed %> h
      <% end %>
    </td>
    <td>
      <% if project.bump_count > 0 %>
        <%= project.bump_count %>
      <% else %>
        &nbsp;
      <% end %>
    </td>
    <td><small><%= project.created_at.localtime.strftime("%b %d, %y")  %></small></td>
    <td>
      <%= link_to 'Bump!', "/projects/#{project.key}/bump", method: :post, class: 'btn btn-mini' %>
      <%= link_to 'Destroy', '/projects/'+project.key, method: :delete, :class => 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>

app/views/projects/_projects_list.html.erb
<table class="table table-hover">
<thead>
  <tr>
    <th>Complete</th>
    <th><%= project_status.capitalize %> Project</th>
    <th></th> <!-- Action buttons -->
    <th>Elapsed</th>
    <th>Bumps</th>
    <th>Created</th>
    </th></th>
  </tr>
</thead>
<tbody>
<% projects.each do |project| %>
  <%= render(partial: 'projects/project', object: project, locals: { project_status: project_status }) %>
<% end %>
</tbody>
</table>

app/views/projects/_status_buttons_canceled.html.erb
      <%= link_to 'Back to Maybe', '/projects/'+project.key+'/status/someday', method: :post, :class => 'btn btn-mini' %>
      <%= link_to 'Back to Idea', '/projects/'+project.key+'/status/idea', method: :post, :class => 'btn btn-mini' %>
      

app/views/projects/_status_buttons_completed.html.erb
      <%= link_to 'Not Done!', '/projects/'+project.key+'/status/active', method: :post, :class => 'btn btn-mini' %>
      <%= link_to 'Cancel', '/projects/'+project.key+'/status/canceled', method: :post, :class => 'btn btn-mini' %>
      

app/views/projects/_status_buttons_someday.html.erb
      <%= link_to 'Focus', '/projects/'+project.key+'/status/active', method: :post, :class => 'btn btn-mini' %>
      <%= link_to 'Done!', '/projects/'+project.key+'/status/completed', method: :post, :class => 'btn btn-mini' %>
      <%= link_to 'Cancel', '/projects/'+project.key+'/status/canceled', method: :post, :class => 'btn btn-mini' %>

app/views/projects/completed.html.erb
<h1>Completed Projects</h1>

<table class="table table-striped table-hover">
<thead>
  <tr>
    <th>Project</th>
    <th></th>
    <th></th> <!-- Action buttons -->
    <th>Elapsed</th>
    <th>Completed</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @completed_projects.each do |project| %>
  <%= render(partial: 'project', object: project, locals: { project_status: :completed }) %>
<% end %>
</tbody>
</table>

app/views/projects/edit.html.erb
<% content_for :title, "LF: #{@project.name} (edit)" %>

<h3>Edit Project</h3>
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% content_for :title, "LF: Projects" %>

<h1>Projects</h1>

<%= render partial: 'new', locals: { area: :soul } %>

<h3>Active</h3>
<%= render(partial: 'projects_list', locals: { projects: @active_projects, project_status: :active }) %>

<br />

<h3>Someday/Maybe</h3>
<%= render(partial: 'projects_list', locals: { projects: @someday_projects, project_status: :someday }) %>

<br />

<h3>Ideas/Hopper</h3>
<%= render(partial: 'projects_list', locals: { projects: @idea_projects, project_status: :idea }) %>

<br />

<%= link_to 'New Project', new_project_path, :class => 'btn' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/set_goals.html.erb
<h4><%= @project.name %> - Goals</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Active Goals</th>
    </tr>
  </thead>
  <tbody>
    <% @active_goals.each do |goal| %>
      <% goal_selected = @goal_ids.include? goal.key %>
      <tr>
        <td><%= check_box_tag goal.key, '1', goal_selected, :data => {'project' => @project.key}, :class => 'project_goal_checkbox' %></td>
        <td><%= link_to goal.name, edit_goal_path(goal) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <div style="margin-top: 1em;">
   <%= link_to 'Done', @project, class: 'btn-mini btn' %>
  </div>

app/views/projects/show.html.erb
<% content_for :title, "LF: #{@project.name}" %>

<%= link_to '< Projects', projects_path, :class => 'btn btn-mini'  %> &nbsp;
<%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-mini'  %>

<%= link_to 'Make Current Focus', edit_current_focus_path(:focus_type => 'Project', :focus_key => @project.key), 
  :method => :post, :class => 'btn btn-mini btn-info'  %>

<h4><%= @project.name %></h4>

<dl class="dl-horizontal">
  <dt>Action:</dt>
  <dd>
    <% if @next_action.present? %>
      <a href="#<%= @next_action.key %>"><%= @next_action.name %></a>
    <% else %>
     -
    <% end %>
  <dt>URL:</dt>
  <dd>
    <% if @project.url.present? %>
      <a href="<%= @project.url %>"><%= @project.url %></a>
    <% else %>
      -
    <% end %>
  </dd>
<% if !@project.description.nil? and !@project.description.empty? %>
  <dt>Description:</dt>
  <dd><%= raw(@project.description) %></dd>
<% end %>
  <dt>Complete:</dt>
  <dd><%= @completed_items.count %> / <%= @num_action_items_total %> action items</dd>
  <dt>Status:</dt>
  <dd><%= @project.status.capitalize %>
  <%= render(partial: 'projects/status_buttons_'+@project.status.to_s, locals: { project: @project } ) %>
  </dd>
  <dt>Area:</dt>
  <dd><%= @project.area.capitalize %></dd>
  <dt>Links:</dt>
  <dd><a href="#links_table"><%= @links.count %></a></dd>
  <dt>Created:</dt>
  <dd><%= @project.created_at.localtime.strftime("%b %d, %Y, %l:%M %P") %></dd>
  <dt>Bumped:</dt>
  <dd><%= @project.bump_count %> times</dd>
  
  <br />
  <dt>Elapsed Time:</dt>
  <dd><%= @elapsed_time_total %> hrs</dd>
</dl>

<%= render(partial: 'projects/goals_served', locals: { project: @project, goals_served: @goals_served } ) %>

<%= form_for(Question.new, :html => { :class => "form-inline inline form-nomargin"}) do |f| %>
  <%= f.text_field :name, :class => "question", :tabindex => 1 %>
  <%= f.hidden_field :parent_type, value: :project %>
  <%= f.hidden_field :parent_key, value: @project.key %>
  <%= f.submit 'Add Question', :class=> "question btn" %>
<% end %>
<%= render(partial: 'questions/list', locals: {questions: @questions}) %>

<% if @completed_items.count > 0 %> 
<div style="margin: 1em 0px;">
  <a href="javascript:void(0)" id="reveal_completed">
    <i class="icon-plus-sign"></i>
    <%= @completed_items.count %> completed items.
    <% if @elapsed_time_completed > 0 %>
    Elapsed Time: <%= @elapsed_time_completed %> hrs.
    <% end %>
  </a>
</div>
<% else %>
<br />
<% end %>

<%= form_for(ActionItem.new, :html => { :class => "form-inline form-nomargin"}) do |f| %>
  <%= f.text_field :name, :class => "action_item", :tabindex => 2, :autofocus => true %>
  url:
  <%= text_field_tag :url, nil, :tabindex => 3 %>
  <%= f.hidden_field :mywn_category, value: :someday %>
  <%= f.hidden_field :parent_type, value: :project %>
  <%= f.hidden_field :parent_key, value: @project.key %>
  <%= f.hidden_field :area, value: @project.area %>
  <%= f.submit 'Add Item', :class=> "action_item btn" %>
<% end %>

<div class="hidden" id="action_items_hidden">
<table class="table table-striped table-hover">
<thead>
  <tr>
    <th></th>
    <th>Item</th>
    <th>Completed</th>
    <th>Bumped</th>
    <th>Elapsed</th>
    <th>Created</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @completed_items.each do |action_item| %>
  <% links = action_item.links %>
  <%= render(partial: 'action_item', locals: {action_item: action_item, links: links}) %>
<% end %>
</tbody>
</table>
</div>

<table class="table table-striped table-hover">
<thead>
  <tr>
    <th></th>
    <th>Action Items (<%= @action_items.count %>)</th>
    <th><!-- action buttons --></th>
    <th>Bumped</th>
    <th>Elapsed</th>
    <th>Created</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @action_items.each do |action_item| %>
  <% links = action_item.links %>
  <%= render(partial: 'action_item', locals: {action_item: action_item, links: links}) %>
<% end %>
</tbody>
</table>
<br />
<%= render(partial: 'web_links/list', locals: {parent_type: :project, parent_key: @project.key, links: @links, starting_index: 3}) %>