config/routes.rb
LifeAdvisor::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "user_home/index"
	get 'home' => "user_home#index"
  get "welcome/index"

	root :to => 'action_items#index'

  controller :action_items do
    get 'action_items/completed' => :completed
    get 'action_items/all' => :all
    post 'action_items/toggle_done/:id' => :toggle_done
    post 'action_items/:id/category/:category' => :category_update
    post 'action_items/category_update_all' => :category_update_all
    post 'action_items/:id/bump' => :bump
    put 'action_items/:id/bump' => :bump
    put 'action_items/:id/to_link' => :to_link
  end
  resources :action_items
  resources :questions
  controller :questions do
    post 'questions/:id/bump' => :bump
  end
  
  resources :answers
  resources :people
  
  controller :web_links do
    get 'web_links/bookmark' => :bookmark
    post 'web_links/bookmark' => :create_bookmark
    put 'web_links/:id/to_action_item' => :to_action_item
  end
  
  controller :projects do
    get 'projects/completed'
    get 'projects/canceled'
    post 'projects/:id/status/:status' => :status_update
    get 'projects/:id/set_goals' => :set_goals
    post 'projects/:project_key/serve_goal_toggle/:goal_key' => :serve_goal_toggle
    post 'projects/:id/bump' => :bump
  end
  resources :projects
  resources :history
  resources :web_links
  resources :thoughts
  resources :goals
  

  
  controller :focus do
    get 'focus/:area' => :focus_area
  end

  controller :goals do
    post 'goals/:id/bump' => :bump
  end

  resources :current_focus do
    collection do
      post 'edit'
      post 'reset'
    end
  end
  

  

end

app/models/thought.rb
require 'RippleSearch'
require 'Parentable'

class Thought
  include Ripple::Document
  extend RippleSearch
  include Parentable
  
  property :name, String, :presence => true
  timestamps!
  before_create :enforce_default_day_parent
  before_update :enforce_default_day_parent
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all.sort! { |a,b| b.created_at <=> a.created_at } 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thoughts }
    end
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    @thought = Thought.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/new
  # GET /thoughts/new.json
  def new
    @thought = Thought.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thought }
    end
  end

  # GET /thoughts/1/edit
  def edit
    @thought = Thought.find(params[:id])
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.new(params[:thought].permit(:name, :parent_type, :parent_key))
    if @thought.parent_type == 'project'
      project = Project.find(@thought.parent_key)
      redirect_url = project_path(project) + '#thoughts_table'
    else
      redirect_url = thoughts_url
    end

    respond_to do |format|
      if @thought.save
        format.html { redirect_to redirect_url, notice: 'Thought was successfully created.' }
        format.json { render json: @thought, status: :created, location: @thought }
      else
        format.html { render action: "new" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thoughts/1
  # PUT /thoughts/1.json
  def update
    @thought = Thought.find(params[:id])
    if @thought.parent_type == 'project'
      project = Project.find(@thought.parent_key)
      redirect_url = project_path(project) + '#thoughts_table'
    else
      redirect_url = thoughts_url
    end

    respond_to do |format|
      if @thought.update_attributes(params[:thought].permit(:name, :parent_type, :parent_key))
        format.html { redirect_to redirect_url, notice: 'Thought was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought = Thought.find(params[:id])
    if @thought.parent_type == 'project'
      project = Project.find(@thought.parent_key)
      redirect_url = project_path(project) + '#thoughts_table'
    else
      redirect_url = thoughts_url
    end
    @thought.destroy

    respond_to do |format|
      format.html { redirect_to redirect_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/thoughts/_form.html.erb
<%= form_for(@thought, :html => { :class => "form-horizontal"}) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
  <%= f.label :name, class: "control-label" %>
  <div class="controls">
    <%= f.text_field :name, :class=> "action_item input-xxlarge" %>
  </div>
</div>

<% if @parent %>
<div class="control-group">
  <%= label_tag '', 'Parent', class: "control-label" %>
  <div class="controls">
    <%= link_to @parent.name, url_for(@parent) %>
  </div>
</div>
<% end %>

<div class="control-group">
  <div class="actions controls">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/thoughts/_new.html.erb
<%= form_for(Thought.new, :html => { :class => "form-inline inline text-center"}) do |f| %>
    <%= label_tag :name, 'Pensieve', class: "control-label" %>
    <%= f.text_area :name, :class=> "thought span4", :rows => 2, :tabindex => tab_index, :autofocus => true %>
    <%= f.hidden_field :parent_type, value: 'day' %>
    <%= f.hidden_field :parent_key, value: 'today' %>
    <%= f.submit 'Save', :class=> "thought btn", :tabindex => tab_index+1 %>
<% end %>

app/views/thoughts/_thought.html.erb
  <tr>
    <td>
      <%= link_to 'Edit', edit_thought_path(thought), :class => 'btn btn-mini' %></td>
    <td class="nowrap"><small><%= thought.created_at.localtime.strftime("%b %d, %y")  %></small></td>
    <td>
      <% if thought.parent_type == 'project' %>
        <span class="area-<%= thought.area %>">[ <%= link_to 'proj', '/projects/'+thought.parent_key %> ]</span>
      <% end %>
      <div id="thought-<%= thought.key %>" style="width: 80%;"><%= auto_link(thought.name) %></div>
    </td>
  </tr>

app/views/thoughts/edit.html.erb
<h1>Editing thought</h1>
<%= link_to 'Delete', '/thoughts/'+@thought.key, method: :delete, :class => 'btn btn-mini btn-danger',
      data: { confirm: 'Are you sure?' } %>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<h1 class="text-center">Thoughts</h1>

<%= render partial: 'thoughts/new', locals: { tab_index: 1 } %>

<table class="table table-hover thoughts">
  <tbody>
<% @thoughts.each do |thought| %>
  <%= render(partial: 'thoughts/thought', object: thought) %>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Thought', new_thought_path, :class => 'btn'  %>

app/views/thoughts/new.html.erb
<h1>New thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>