config/routes.rb
LifeAdvisor::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "user_home/index"
	get 'home' => "user_home#index"
  get "welcome/index"

	root :to => 'action_items#index'

  controller :action_items do
    get 'action_items/completed' => :completed
    get 'action_items/all' => :all
    post 'action_items/toggle_done/:id' => :toggle_done
    post 'action_items/:id/category/:category' => :category_update
    post 'action_items/category_update_all' => :category_update_all
    post 'action_items/:id/bump' => :bump
    put 'action_items/:id/bump' => :bump
    put 'action_items/:id/to_link' => :to_link
  end
  resources :action_items
  resources :questions
  controller :questions do
    post 'questions/:id/bump' => :bump
  end
  
  resources :answers
  resources :people
  
  controller :web_links do
    get 'web_links/bookmark' => :bookmark
    post 'web_links/bookmark' => :create_bookmark
    put 'web_links/:id/to_action_item' => :to_action_item
  end
  
  controller :projects do
    get 'projects/completed'
    get 'projects/canceled'
    post 'projects/:id/status/:status' => :status_update
    get 'projects/:id/set_goals' => :set_goals
    post 'projects/:project_key/serve_goal_toggle/:goal_key' => :serve_goal_toggle
    post 'projects/:id/bump' => :bump
  end
  resources :projects
  resources :history
  resources :web_links
  resources :thoughts
  resources :goals
  

  
  controller :focus do
    get 'focus/:area' => :focus_area
  end

  controller :goals do
    post 'goals/:id/bump' => :bump
  end

  resources :current_focus do
    collection do
      post 'edit'
      post 'reset'
    end
  end
  

  

end

app/models/web_link.rb
require 'RippleSearch'
require 'Parentable'

class WebLink
  include Ripple::Document
  extend RippleSearch
  include Parentable
  
  property :name, String
  property :url, String, :presence => true
  property :description, String
  timestamps!
  
  before_create :enforce_default_day_parent
  before_update :enforce_default_day_parent

  def name_display
    if self.name.blank? and self.url.present?
      return self.url.truncate(50)
    end
    self.name
  end
  
  # Initialize a new WebLink from an ActionItem instance
  def self.from_action_item(action_item)
    link = WebLink.new name: action_item.name
    link.url = action_item.links.first.url
    link.parent_type = action_item.parent_type
    link.parent_key = action_item.parent_key
    link
  end
end

app/controllers/web_links_controller.rb
class WebLinksController < ApplicationController
  layout 'bookmark', :only => [:bookmark]
  
  # GET /web_links/bookmark
  # Bookmarklet code:
  # <code>
  # javascript:window.open('http://localhost:3000/web_links/bookmark?url='+encodeURIComponent(location.href)+'&name='+encodeURIComponent(document.title),
  # 'newWindowName','width=775,height=450,scrollbars=no,status=no,titlebar=no,toolbar=no');void(0);
  # </code>
  def bookmark
    @web_link = WebLink.new(params.permit([:name, :url]))
  end
  
  # POST /web_links/bookmark
  def create_bookmark
    @current_focus = Elefsis.current_focus
    @web_link = @current_focus.new_link(params[:web_link].permit(:name, :url, :description))
    
    respond_to do |format|
      if @web_link.save
        format.html { head :ok }
        format.js { head :ok }
      else
        format.json { render json: @web_link.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /web_links
  # GET /web_links.json
  def index
    @web_links = WebLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @web_links }
    end
  end

  # GET /web_links/1
  # GET /web_links/1.json
  def show
    @web_link = WebLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @web_link }
    end
  end

  # GET /web_links/new
  # GET /web_links/new.json
  def new
    @web_link = WebLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @web_link }
    end
  end

  # GET /web_links/1/edit
  def edit
    @web_link = WebLink.find(params[:id])
  end

  # POST /web_links
  # POST /web_links.json
  def create
    @web_link = WebLink.new(web_link_params)
    if @web_link.parent_type == 'project'
      project = Project.find(@web_link.parent_key)
      redirect_url = project_path(project) + '#links_table'
    elsif @web_link.parent_type == 'action_item'
      action_item = ActionItem.find(@web_link.parent_key)
      redirect_url = action_item_path(action_item) + '#links_table'
    elsif @web_link.parent_type == 'question'
            question = Question.find(@web_link.parent_key)
            redirect_url = question_path(question) + '#links_table'
    else
      redirect_url = web_links_url
    end
    
    respond_to do |format|
      if @web_link.save
        format.html { redirect_to redirect_url, notice: 'Link was successfully created.' }
        format.json { render json: @web_link, status: :created, location: @web_link }
      else
        format.html { render action: "new" }
        format.json { render json: @web_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /web_links/1/to_action_item
  def to_action_item
    @web_link = WebLink.find(params[:id])
    redirect_url = @web_link.parent_url
    
    respond_to do |format|
      action_item = ActionItem.from_web_link @web_link
      if action_item.save
        action_item.save_related()
        @web_link.destroy!
      end
      format.html { redirect_to redirect_url, notice: 'Converted to ActionItem' }
    end
  end
  
  # PUT /web_links/1
  # PUT /web_links/1.json
  def update
    @web_link = WebLink.find(params[:id])
    if @web_link.parent_type == 'project'
      project = Project.find(@web_link.parent_key)
      redirect_url = project_path(project) + '#links_table'
    elsif @web_link.parent_type == 'action_item'
        action_item = ActionItem.find(@web_link.parent_key)
        redirect_url = action_item_path(action_item) + '#links_table'
    elsif @web_link.parent_type == 'question'
          question = Question.find(@web_link.parent_key)
          redirect_url = question_path(question) + '#links_table'
    else
      redirect_url = web_links_url
    end
    
    respond_to do |format|
      if @web_link.update_attributes(web_link_params)
        format.html { redirect_to redirect_url, notice: 'Web link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @web_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_links/1
  # DELETE /web_links/1.json
  def destroy
    @web_link = WebLink.find(params[:id])
    if @web_link.parent_type == 'project'
      project = Project.find(@web_link.parent_key)
      redirect_url = project_path(project) + '#links_table'
    elsif @web_link.parent_type == 'action_item'
      action_item = ActionItem.find(@web_link.parent_key)
      redirect_url = action_item_path(action_item) + '#links_table'
    else
      redirect_url = web_links_url
    end
    @web_link.destroy
    respond_to do |format|
      format.html { redirect_to redirect_url }
      format.json { head :no_content }
    end
  end
  
  private
  def web_link_params
    params[:web_link].permit(:name, :url, :description, :parent_type, :parent_key)
  end
end

app/helpers/web_links_helper.rb
module WebLinksHelper
end

app/views/web_links/_form.html.erb
<%= form_for(@web_link) do |f| %>
  <% if @web_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_link.errors.count, "error") %> prohibited this web_link from being saved:</h2>

      <ul>
      <% @web_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :url %>
    <%= f.text_field :url, :class=> "web_link" %><br />

    <%= f.label :name %>
    <%= f.text_field :name, :class=> "web_link" %><br />

  <div class="control-group">
    <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, :class=> "action_item", :rows => 5 %><br />
  </div>

    <div class="clear"><br /></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_links/_form_bookmark.html.erb
<%= form_for @web_link do |f| %>
  <% if @web_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_link.errors.count, "error") %> prohibited this web_link from being saved:</h2>

      <ul>
      <% @web_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :url %>
    <%= f.text_field :url, :class=> "web_link" %><br />

    <%= f.label :name %>
    <%= f.text_field :name, :class=> "web_link" %><br />

  <div class="control-group">
    <%= f.label :description, class: "control-label" %>
  <div class="controls">
    <%= f.text_area :description, :class=> "action_item", :rows => 5 %><br />
  </div>

    <div class="clear"><br /></div>

  <div class="actions">
   <%= link_to 'Bookmark', '#', { id: 'bookmark_form_submit', class: 'btn btn-mini'} %>
  </div>
<% end %>

app/views/web_links/_link.html.erb
  <tr>
    <td><%= link.name  %></td>
    <td>
      <%= link_to link.url, link.url %><br />
      <small><%= link.description %></small>
    </td>
    <td><small><%= link.created_at.localtime.strftime("%b %d, %Y")  %></small></td>
    <td>
      <%= link_to 'Edit', edit_web_link_path(link), :class => 'btn btn-mini' %>
      <%= link_to 'Destroy', '/web_links/'+link.key, method: :delete, :class => 'btn btn-mini btn-danger',
        data: { confirm: 'Are you sure?' } %>
      <br />
      <%= link_to 'To ActionItem', '/web_links/'+link.key+'/to_action_item', method: :put, :class => 'btn btn-mini',
        data: { confirm: 'Convert to ActionItem - Are you sure?' } %>
    </td>
  </tr>

app/views/web_links/_list.html.erb
<%= form_for(WebLink.new, :html => { :class => "form-inline inline form-nomargin"}) do |f| %>
    url <%= f.text_field :url, :class => "link", :tabindex => starting_index %>
    name <%= f.text_field :name, :class => "link", :tabindex => starting_index+1 %>
    <%= f.hidden_field :parent_type, value: parent_type %>
    <%= f.hidden_field :parent_key, value: parent_key %>
    <%= f.submit 'Add Link', :class=> "link btn" %>
<% end %>

<table class="table table-striped table-hover" id="links_table">
<thead>
  <tr>
    <th>Link</th>
    <th></th>
    <th>Added</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% links.each do | link | %>
    <%= render(partial: 'web_links/link', object: link) %>
<% end %>
</tbody>
</table>

app/views/web_links/bookmark.html.erb
<%= render 'form_bookmark' %>

app/views/web_links/edit.html.erb
<h1>Editing web_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_link %> |
<%= link_to 'Back', web_links_path %>

app/views/web_links/index.html.erb
<h1>Listing web_links</h1>

<table class="table table-striped">
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @web_links.each do |web_link| %>
  <tr>
    <td><%= web_link.name %></td>
    <td><%= web_link.url %></td>
    <td><%= link_to 'Show', web_link %></td>
    <td><%= link_to 'Edit', edit_web_link_path(web_link) %></td>
    <td><%= link_to 'Destroy', web_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Web link', new_web_link_path %>

app/views/web_links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', web_links_path %>

app/views/web_links/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_web_link_path(@web_link) %> |
<%= link_to 'Back', web_links_path %>